# configs/extract_tokens.yml
model:
  name: 'dinov3_vith16plus' # 维度 1280
  desc_layer: 28            # 取第 28 层
  return_tokens: True       # 开启 Token 返回模式
  device: 'cuda'
  # 指定本地 dinov3 路径 (根据您的报错日志修正为 dinov3-main)
  local_path: '/home/dell/data/jzl/dinov3-main'

data:
  # 基础路径，脚本会自动追加 /train 或 /test
  data_path: '/home/dell/data/jzl/pipei/EM-CVGL-main/data/University-Release'
  batch_size: 64 # 显存不足可调小
  workers: 4

# 严格遵循 featv13 utils/transform.py 的定义，仅使用字符串键名
transform:
  - Resize256
  #- CenterCrop252
  - ToTensor
  - normalize

# 输出路径
output:
  path: '/home/dell/data/jzl/0-pipei-dinov3/outputs/tokens_v13'