feat_root: '/root/autodl-tmp/0-pipei-dinov3/feats/dinov3_vith16plus'
output_dir: '/root/autodl-tmp/0-pipei-dinov3/outputs/unsupervised_srdae_v12'
save_name: 'srdae_model_v12.pth'

# fusion_layers: [28, 31] #v12
# input_dim: 2560
# latent_dim: 1280

fusion_layers: [22, 26, 30] #v12
input_dim: 3840
latent_dim: 1280

# fusion_layers: [21, 22, 23, 24, 25, 26, 27, 29, 30, 31] #v13 2560    v14 1280
# input_dim: 12800
# latent_dim: 2560

train:
  batch_size: 1024
  epochs: 60
  lr: 0.001
  warmup_epochs: 5
  drop_rate: 0.0       # 0.1 -> 0.0 (Removal)
  
  # Loss Balancing
  lambda_recon: 1.0
  lambda_decov: 80.0   # 保持高去相关
  lambda_orth: 5.0     # 约束
  lambda_sparse: 0.05  # 0.001 -> 0.02 (20倍! 逼迫 Gamma 变小)